version: '3.4'

services:
  restauranttestassignment:
    image: restauranttestassignment
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8999:8999
    env_file:
      - .env
  mongodb:

    image: mongo
    container_name: mongodb
    ports:
      - 2717:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  mongo-express:

    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}